# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squeeze', '0002_link_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(max_length=10),
        ),
    ]
