# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squeeze', '0003_auto_20171116_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
